<a href="https://colab.research.google.com/github/NishanRegmi/machine-learning/blob/main/optuna_hyperparameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import optuna
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [22]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

In [23]:
df = pd.read_csv(url, names=columns)

In [24]:
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [25]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Insulin have 0 as missing value so first fill insulin with mean

In [28]:
# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

df.fillna(df.mean(), inplace=True)

In [29]:
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6    148.0           72.0  ...                     0.627   50        1
1            1     85.0           66.0  ...                     0.351   31        0
2            8    183.0           64.0  ...                     0.672   32        1
3            1     89.0           66.0  ...                     0.167   21        0
4            0    137.0           40.0  ...                     2.288   33        1

[5 rows x 9 columns]

In [39]:
X = df.drop(columns=['Outcome'], axis=1)
y = df['Outcome']

In [40]:
#split into train test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=41)

In [41]:
#normalize the data using standardscaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [42]:
X_train

array([[ 0.69026007,  1.46386914,  0.11413899, ..., -0.82009461,
        -0.5036029 ,  2.96450972],
       [ 0.07144595,  0.09075822, -0.22019901, ..., -0.49400992,
         1.95122858,  1.08595408],
       [-0.85677523,  2.36811291, -1.89188903, ..., -0.91933777,
         0.52216597, -0.79260155],
       ...,
       [ 0.69026007, -0.11018484, -1.89188903, ..., -0.74920663,
         2.45972939,  0.01249372],
       [-0.23796111, -0.34461841,  0.11413899, ..., -0.11121486,
        -0.81630167, -0.70314652],
       [-0.23796111, -0.3111279 , -2.39339604, ..., -1.41555359,
        -0.98287952, -0.97151161]])

In [43]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [44]:
#defining the objective function
def objective(trial):
  #possible value for hyperparameter
  n_estimators = trial.suggest_int('n_estimators', 50, 200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  #create a model with possible hyperparameter
  model = RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth=max_depth,
      random_state=41
  )
  score = np.mean(cross_val_score(model, X_train, y_train, cv=10, scoring='accuracy'))
  return score

In [46]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())
study.optimize(objective, n_trials=50)

[I 2026-05-18 02:19:45,029] A new study created in memory with name: no-name-465cde4a-faeb-4a98-bd35-36dd92800295
[I 2026-05-18 02:19:47,387] Trial 0 finished with value: 0.7560796645702306 and parameters: {'n_estimators': 118, 'max_depth': 19}. Best is trial 0 with value: 0.7560796645702306.
[I 2026-05-18 02:19:48,905] Trial 1 finished with value: 0.7524109014675053 and parameters: {'n_estimators': 77, 'max_depth': 15}. Best is trial 0 with value: 0.7560796645702306.
[I 2026-05-18 02:19:52,554] Trial 2 finished with value: 0.763591893780573 and parameters: {'n_estimators': 196, 'max_depth': 8}. Best is trial 2 with value: 0.763591893780573.
[I 2026-05-18 02:19:54,882] Trial 3 finished with value: 0.7673305380852551 and parameters: {'n_estimators': 139, 'max_depth': 4}. Best is trial 3 with value: 0.7673305380852551.
[I 2026-05-18 02:19:56,505] Trial 4 finished with value: 0.7655136268343815 and parameters: {'n_estimators': 85, 'max_depth': 8}. Best is trial 3 with value: 0.7673305380852551.
[I 2026-05-18 02:20:00,063] Trial 5 finished with value: 0.7673305380852551 and parameters: {'n_estimators': 195, 'max_depth': 7}. Best is trial 3 with value: 0.7673305380852551.
[I 2026-05-18 02:20:03,087] Trial 6 finished with value: 0.7561146051712089 and parameters: {'n_estimators': 156, 'max_depth': 13}. Best is trial 3 with value: 0.7673305380852551.
[I 2026-05-18 02:20:05,854] Trial 7 finished with value: 0.756114605171209 and parameters: {'n_estimators': 142, 'max_depth': 14}. Best is trial 3 with value: 0.7673305380852551.
[I 2026-05-18 02:20:09,606] Trial 8 finished with value: 0.7542627533193571 and parameters: {'n_estimators': 199, 'max_depth': 9}. Best is trial 3 with value: 0.7673305380852551.
[I 2026-05-18 02:20:11,094] Trial 9 finished with value: 0.771069182389937 and parameters: {'n_estimators': 89, 'max_depth': 4}. Best is trial 9 with value: 0.771069182389937.
[I 2026-05-18 02:20:11,956] Trial 10 finished with value: 0.7692173305380854 and parameters: {'n_estimators': 52, 'max_depth': 3}. Best is trial 9 with value: 0.771069182389937.
[I 2026-05-18 02:20:12,809] Trial 11 finished with value: 0.7674004192872117 and parameters: {'n_estimators': 51, 'max_depth': 3}. Best is trial 9 with value: 0.771069182389937.
[I 2026-05-18 02:20:13,734] Trial 12 finished with value: 0.7728511530398323 and parameters: {'n_estimators': 51, 'max_depth': 5}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:15,372] Trial 13 finished with value: 0.7636268343815514 and parameters: {'n_estimators': 90, 'max_depth': 6}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:17,410] Trial 14 finished with value: 0.7709993011879804 and parameters: {'n_estimators': 104, 'max_depth': 11}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:18,605] Trial 15 finished with value: 0.769182389937107 and parameters: {'n_estimators': 67, 'max_depth': 5}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:20,671] Trial 16 finished with value: 0.7523759608665269 and parameters: {'n_estimators': 105, 'max_depth': 10}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:21,958] Trial 17 finished with value: 0.7486722571628233 and parameters: {'n_estimators': 64, 'max_depth': 17}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:23,581] Trial 18 finished with value: 0.7655136268343815 and parameters: {'n_estimators': 92, 'max_depth': 5}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:24,822] Trial 19 finished with value: 0.7599231306778477 and parameters: {'n_estimators': 68, 'max_depth': 6}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:27,060] Trial 20 finished with value: 0.7579315164220825 and parameters: {'n_estimators': 114, 'max_depth': 12}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:29,044] Trial 21 finished with value: 0.7579664570230609 and parameters: {'n_estimators': 100, 'max_depth': 16}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:31,573] Trial 22 finished with value: 0.7654437456324248 and parameters: {'n_estimators': 129, 'max_depth': 11}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:33,117] Trial 23 finished with value: 0.7542278127183787 and parameters: {'n_estimators': 79, 'max_depth': 9}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:36,413] Trial 24 finished with value: 0.7486722571628232 and parameters: {'n_estimators': 169, 'max_depth': 20}. Best is trial 12 with value: 0.7728511530398323.
[I 2026-05-18 02:20:38,133] Trial 25 finished with value: 0.7728860936408106 and parameters: {'n_estimators': 103, 'max_depth': 4}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:39,190] Trial 26 finished with value: 0.7672257162823201 and parameters: {'n_estimators': 62, 'max_depth': 4}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:41,293] Trial 27 finished with value: 0.7617749825296996 and parameters: {'n_estimators': 117, 'max_depth': 6}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:42,532] Trial 28 finished with value: 0.7673305380852551 and parameters: {'n_estimators': 76, 'max_depth': 3}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:44,688] Trial 29 finished with value: 0.7655136268343815 and parameters: {'n_estimators': 123, 'max_depth': 5}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:46,483] Trial 30 finished with value: 0.7691125087351504 and parameters: {'n_estimators': 96, 'max_depth': 7}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:48,619] Trial 31 finished with value: 0.7579315164220825 and parameters: {'n_estimators': 109, 'max_depth': 18}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:50,344] Trial 32 finished with value: 0.7728860936408106 and parameters: {'n_estimators': 103, 'max_depth': 4}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:52,519] Trial 33 finished with value: 0.769182389937107 and parameters: {'n_estimators': 130, 'max_depth': 4}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:53,953] Trial 34 finished with value: 0.769182389937107 and parameters: {'n_estimators': 84, 'max_depth': 4}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:56,559] Trial 35 finished with value: 0.7673305380852551 and parameters: {'n_estimators': 141, 'max_depth': 7}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:57,900] Trial 36 finished with value: 0.7710342417889589 and parameters: {'n_estimators': 76, 'max_depth': 5}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:20:59,997] Trial 37 finished with value: 0.7636268343815512 and parameters: {'n_estimators': 111, 'max_depth': 8}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:21:01,371] Trial 38 finished with value: 0.769182389937107 and parameters: {'n_estimators': 84, 'max_depth': 3}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:21:04,145] Trial 39 finished with value: 0.7636268343815514 and parameters: {'n_estimators': 154, 'max_depth': 6}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:21:05,951] Trial 40 finished with value: 0.7728511530398323 and parameters: {'n_estimators': 97, 'max_depth': 7}. Best is trial 25 with value: 0.7728860936408106.
[I 2026-05-18 02:21:07,638] Trial 41 finished with value: 0.7729210342417889 and parameters: {'n_estimators': 99, 'max_depth': 4}. Best is trial 41 with value: 0.7729210342417889.
[I 2026-05-18 02:21:09,457] Trial 42 finished with value: 0.7691125087351504 and parameters: {'n_estimators': 98, 'max_depth': 7}. Best is trial 41 with value: 0.7729210342417889.
[I 2026-05-18 02:21:11,504] Trial 43 finished with value: 0.7729559748427673 and parameters: {'n_estimators': 122, 'max_depth': 4}. Best is trial 43 with value: 0.7729559748427673.
[I 2026-05-18 02:21:13,549] Trial 44 finished with value: 0.7729559748427673 and parameters: {'n_estimators': 122, 'max_depth': 4}. Best is trial 43 with value: 0.7729559748427673.
[I 2026-05-18 02:21:15,574] Trial 45 finished with value: 0.7673654786862334 and parameters: {'n_estimators': 125, 'max_depth': 3}. Best is trial 43 with value: 0.7729559748427673.
[I 2026-05-18 02:21:17,616] Trial 46 finished with value: 0.7729559748427673 and parameters: {'n_estimators': 121, 'max_depth': 4}. Best is trial 43 with value: 0.7729559748427673.
[I 2026-05-18 02:21:19,780] Trial 47 finished with value: 0.7673654786862334 and parameters: {'n_estimators': 134, 'max_depth': 3}. Best is trial 43 with value: 0.7729559748427673.
[I 2026-05-18 02:21:22,238] Trial 48 finished with value: 0.771069182389937 and parameters: {'n_estimators': 148, 'max_depth': 4}. Best is trial 43 with value: 0.7729559748427673.
[I 2026-05-18 02:21:24,601] Trial 49 finished with value: 0.7542976939203354 and parameters: {'n_estimators': 124, 'max_depth': 9}. Best is trial 43 with value: 0.7729559748427673.

In [47]:
print("Best accuracy: ", study.best_trial.value)
print("Best parameter: ", study.best_trial.params)

Best accuracy:  0.7729559748427673
Best parameter:  {'n_estimators': 122, 'max_depth': 4}

In [48]:
#using the best parameter value, again train the model

classifier = RandomForestClassifier(n_estimators=122, max_depth=4, random_state=41)

In [49]:
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [50]:
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(y_test, y_pred))

Accuracy:  0.7402597402597403

**Samplers in Optuna**

In [51]:
#defining the objective function
def objective(trial):
  #possible value for hyperparameter
  n_estimators = trial.suggest_int('n_estimators', 50, 200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  #create a model with possible hyperparameter
  model = RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth=max_depth,
      random_state=41
  )
  score = np.mean(cross_val_score(model, X_train, y_train, cv=10, scoring='accuracy'))
  return score

In [52]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())
study.optimize(objective, n_trials=50)

[I 2026-05-18 02:34:11,598] A new study created in memory with name: no-name-0fd8e537-ecd2-4db8-9738-d6fed842fde7
[I 2026-05-18 02:34:15,408] Trial 0 finished with value: 0.7598183088749126 and parameters: {'n_estimators': 196, 'max_depth': 10}. Best is trial 0 with value: 0.7598183088749126.
[I 2026-05-18 02:34:16,477] Trial 1 finished with value: 0.7635918937805731 and parameters: {'n_estimators': 53, 'max_depth': 11}. Best is trial 1 with value: 0.7635918937805731.
[I 2026-05-18 02:34:19,081] Trial 2 finished with value: 0.7673305380852551 and parameters: {'n_estimators': 141, 'max_depth': 7}. Best is trial 2 with value: 0.7673305380852551.
[I 2026-05-18 02:34:20,520] Trial 3 finished with value: 0.7579664570230608 and parameters: {'n_estimators': 72, 'max_depth': 14}. Best is trial 2 with value: 0.7673305380852551.
[I 2026-05-18 02:34:22,764] Trial 4 finished with value: 0.7523759608665269 and parameters: {'n_estimators': 113, 'max_depth': 12}. Best is trial 2 with value: 0.7673305380852551.
[I 2026-05-18 02:34:26,172] Trial 5 finished with value: 0.763591893780573 and parameters: {'n_estimators': 191, 'max_depth': 6}. Best is trial 2 with value: 0.7673305380852551.
[I 2026-05-18 02:34:28,680] Trial 6 finished with value: 0.7542627533193571 and parameters: {'n_estimators': 128, 'max_depth': 14}. Best is trial 2 with value: 0.7673305380852551.
[I 2026-05-18 02:34:30,074] Trial 7 finished with value: 0.7710342417889587 and parameters: {'n_estimators': 83, 'max_depth': 4}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:32,251] Trial 8 finished with value: 0.756114605171209 and parameters: {'n_estimators': 111, 'max_depth': 20}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:33,679] Trial 9 finished with value: 0.7486373165618448 and parameters: {'n_estimators': 72, 'max_depth': 15}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:36,479] Trial 10 finished with value: 0.7654437456324249 and parameters: {'n_estimators': 153, 'max_depth': 7}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:38,283] Trial 11 finished with value: 0.7598183088749126 and parameters: {'n_estimators': 94, 'max_depth': 9}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:40,467] Trial 12 finished with value: 0.7654786862334031 and parameters: {'n_estimators': 116, 'max_depth': 8}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:44,306] Trial 13 finished with value: 0.756114605171209 and parameters: {'n_estimators': 195, 'max_depth': 17}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:46,444] Trial 14 finished with value: 0.7598881900768694 and parameters: {'n_estimators': 110, 'max_depth': 9}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:49,924] Trial 15 finished with value: 0.750524109014675 and parameters: {'n_estimators': 181, 'max_depth': 10}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:52,587] Trial 16 finished with value: 0.7579664570230606 and parameters: {'n_estimators': 130, 'max_depth': 14}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:55,497] Trial 17 finished with value: 0.763591893780573 and parameters: {'n_estimators': 158, 'max_depth': 7}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:56,988] Trial 18 finished with value: 0.756114605171209 and parameters: {'n_estimators': 77, 'max_depth': 9}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:34:59,931] Trial 19 finished with value: 0.7542627533193571 and parameters: {'n_estimators': 150, 'max_depth': 19}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:03,035] Trial 20 finished with value: 0.7654437456324249 and parameters: {'n_estimators': 173, 'max_depth': 6}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:04,830] Trial 21 finished with value: 0.756009783368274 and parameters: {'n_estimators': 91, 'max_depth': 13}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:08,284] Trial 22 finished with value: 0.750524109014675 and parameters: {'n_estimators': 175, 'max_depth': 19}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:11,250] Trial 23 finished with value: 0.7523410202655485 and parameters: {'n_estimators': 150, 'max_depth': 17}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:12,144] Trial 24 finished with value: 0.769182389937107 and parameters: {'n_estimators': 52, 'max_depth': 4}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:15,114] Trial 25 finished with value: 0.752480782669462 and parameters: {'n_estimators': 151, 'max_depth': 15}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:16,549] Trial 26 finished with value: 0.7654786862334031 and parameters: {'n_estimators': 82, 'max_depth': 5}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:18,032] Trial 27 finished with value: 0.7542278127183787 and parameters: {'n_estimators': 75, 'max_depth': 14}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:19,275] Trial 28 finished with value: 0.750524109014675 and parameters: {'n_estimators': 63, 'max_depth': 18}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:21,330] Trial 29 finished with value: 0.7616701607267645 and parameters: {'n_estimators': 105, 'max_depth': 13}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:22,653] Trial 30 finished with value: 0.7636268343815514 and parameters: {'n_estimators': 82, 'max_depth': 3}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:24,273] Trial 31 finished with value: 0.756114605171209 and parameters: {'n_estimators': 82, 'max_depth': 19}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:25,700] Trial 32 finished with value: 0.7709993011879804 and parameters: {'n_estimators': 76, 'max_depth': 7}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:27,357] Trial 33 finished with value: 0.7709294199860238 and parameters: {'n_estimators': 89, 'max_depth': 7}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:29,885] Trial 34 finished with value: 0.7673305380852551 and parameters: {'n_estimators': 152, 'max_depth': 4}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:32,001] Trial 35 finished with value: 0.7579315164220825 and parameters: {'n_estimators': 108, 'max_depth': 19}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:34,208] Trial 36 finished with value: 0.7580363382250175 and parameters: {'n_estimators': 116, 'max_depth': 9}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:37,083] Trial 37 finished with value: 0.763591893780573 and parameters: {'n_estimators': 157, 'max_depth': 7}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:38,822] Trial 38 finished with value: 0.7636268343815514 and parameters: {'n_estimators': 99, 'max_depth': 5}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:40,553] Trial 39 finished with value: 0.7617400419287212 and parameters: {'n_estimators': 96, 'max_depth': 6}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:43,830] Trial 40 finished with value: 0.756114605171209 and parameters: {'n_estimators': 169, 'max_depth': 12}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:46,439] Trial 41 finished with value: 0.7636268343815514 and parameters: {'n_estimators': 146, 'max_depth': 6}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:48,383] Trial 42 finished with value: 0.7542976939203354 and parameters: {'n_estimators': 101, 'max_depth': 9}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:49,829] Trial 43 finished with value: 0.7709993011879804 and parameters: {'n_estimators': 75, 'max_depth': 7}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:51,141] Trial 44 finished with value: 0.743046820405311 and parameters: {'n_estimators': 65, 'max_depth': 15}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:52,298] Trial 45 finished with value: 0.7412299091544374 and parameters: {'n_estimators': 58, 'max_depth': 13}. Best is trial 7 with value: 0.7710342417889587.
[I 2026-05-18 02:35:55,503] Trial 46 finished with value: 0.7766247379454926 and parameters: {'n_estimators': 193, 'max_depth': 4}. Best is trial 46 with value: 0.7766247379454926.
[I 2026-05-18 02:35:57,535] Trial 47 finished with value: 0.7579664570230609 and parameters: {'n_estimators': 103, 'max_depth': 18}. Best is trial 46 with value: 0.7766247379454926.
[I 2026-05-18 02:36:00,517] Trial 48 finished with value: 0.7561495457721873 and parameters: {'n_estimators': 156, 'max_depth': 10}. Best is trial 46 with value: 0.7766247379454926.
[I 2026-05-18 02:36:02,503] Trial 49 finished with value: 0.769182389937107 and parameters: {'n_estimators': 115, 'max_depth': 5}. Best is trial 46 with value: 0.7766247379454926.

In [53]:
print(f'Best accuracy: {study.best_trial.value}')
print(f'Best parameter: {study.best_trial.params}')

Best accuracy: 0.7766247379454926
Best parameter: {'n_estimators': 193, 'max_depth': 4}

**Optuna Visualizations**

In [54]:
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [55]:
#optimization history
plot_optimization_history(study).show()

In [56]:
#parallel cordinates plot
plot_parallel_coordinate(study).show()

In [57]:
#slice plot
plot_slice(study).show()

In [58]:
#contour plot
plot_contour(study).show()

In [59]:
#important parameter
plot_param_importances(study).show()

**Optimiziing multiple ML model**

In [60]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [62]:
def objective(trial):
  #define multiple model
  classifier_name = trial.suggest_categorical('classifier', ['svm', 'randomforest', 'gradientboost'])

  if classifier_name == 'svm':
    c = trial.suggest_float('C', 0.1, 100, log=True)
    kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
    gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

    model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

  elif classifier_name == 'randomforest':
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
    bootstrap = trial.suggest_categorical('bootstrap', [True, False])

    model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42)
  elif classifier_name == 'gradientboost':
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

    model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42)

  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
  return score

In [63]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

[I 2026-05-18 03:04:19,263] A new study created in memory with name: no-name-e31b7057-f43d-47d1-9d18-e3f65152230f
[I 2026-05-18 03:04:20,451] Trial 0 finished with value: 0.7541899441340782 and parameters: {'classifier': 'gradientboost', 'n_estimators': 116, 'learning_rate': 0.12248312943545496, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.7541899441340782.
[I 2026-05-18 03:04:20,474] Trial 1 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.4049644250283043, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 1 with value: 0.7765363128491619.
[I 2026-05-18 03:04:20,500] Trial 2 finished with value: 0.7392923649906891 and parameters: {'classifier': 'svm', 'C': 3.168322941081726, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 1 with value: 0.7765363128491619.
[I 2026-05-18 03:04:22,303] Trial 3 finished with value: 0.7560521415270017 and parameters: {'classifier': 'gradientboost', 'n_estimators': 161, 'learning_rate': 0.12620253079883528, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 1 with value: 0.7765363128491619.
[I 2026-05-18 03:04:23,581] Trial 4 finished with value: 0.7597765363128492 and parameters: {'classifier': 'randomforest', 'n_estimators': 269, 'max_depth': 4, 'min_samples_split': 4, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 1 with value: 0.7765363128491619.
[I 2026-05-18 03:04:23,605] Trial 5 finished with value: 0.7039106145251397 and parameters: {'classifier': 'svm', 'C': 14.92772575866912, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 1 with value: 0.7765363128491619.
[I 2026-05-18 03:04:24,763] Trial 6 finished with value: 0.7597765363128491 and parameters: {'classifier': 'randomforest', 'n_estimators': 239, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 1 with value: 0.7765363128491619.
[I 2026-05-18 03:04:25,263] Trial 7 finished with value: 0.7560521415270017 and parameters: {'classifier': 'randomforest', 'n_estimators': 121, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.7765363128491619.
[I 2026-05-18 03:04:25,287] Trial 8 finished with value: 0.696461824953445 and parameters: {'classifier': 'svm', 'C': 0.12197970711453351, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 1 with value: 0.7765363128491619.
[I 2026-05-18 03:04:25,634] Trial 9 finished with value: 0.7486033519553073 and parameters: {'classifier': 'randomforest', 'n_estimators': 81, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 1 with value: 0.7765363128491619.
[I 2026-05-18 03:04:25,660] Trial 10 finished with value: 0.7783985102420856 and parameters: {'classifier': 'svm', 'C': 0.15838506998906784, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:25,685] Trial 11 finished with value: 0.7783985102420856 and parameters: {'classifier': 'svm', 'C': 0.12960227878990682, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:25,710] Trial 12 finished with value: 0.7783985102420856 and parameters: {'classifier': 'svm', 'C': 0.1019897745995935, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:25,740] Trial 13 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 1.048395981443016, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:25,771] Trial 14 finished with value: 0.7765363128491621 and parameters: {'classifier': 'svm', 'C': 0.5570490756827724, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:26,242] Trial 15 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 71.99204860634833, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:29,493] Trial 16 finished with value: 0.7337057728119181 and parameters: {'classifier': 'gradientboost', 'n_estimators': 206, 'learning_rate': 0.010492075056320853, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:29,519] Trial 17 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.290196826120255, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:29,550] Trial 18 finished with value: 0.7579143389199254 and parameters: {'classifier': 'svm', 'C': 2.126694871394699, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:30,517] Trial 19 finished with value: 0.7523277467411545 and parameters: {'classifier': 'gradientboost', 'n_estimators': 52, 'learning_rate': 0.016262742205090795, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:30,552] Trial 20 finished with value: 0.7635009310986964 and parameters: {'classifier': 'svm', 'C': 0.19336771410419676, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 10 with value: 0.7783985102420856.
[I 2026-05-18 03:04:30,577] Trial 21 finished with value: 0.7802607076350093 and parameters: {'classifier': 'svm', 'C': 0.1074710140811938, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:30,601] Trial 22 finished with value: 0.7802607076350093 and parameters: {'classifier': 'svm', 'C': 0.10767235745939517, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:30,628] Trial 23 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.6001209874807937, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:30,652] Trial 24 finished with value: 0.7783985102420856 and parameters: {'classifier': 'svm', 'C': 0.10001875572768007, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:30,678] Trial 25 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.2666052749395742, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:30,712] Trial 26 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 1.621289628818614, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:30,746] Trial 27 finished with value: 0.739292364990689 and parameters: {'classifier': 'svm', 'C': 5.508254263081858, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:33,461] Trial 28 finished with value: 0.7411545623836128 and parameters: {'classifier': 'gradientboost', 'n_estimators': 298, 'learning_rate': 0.27325380573501395, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:34,310] Trial 29 finished with value: 0.7597765363128491 and parameters: {'classifier': 'randomforest', 'n_estimators': 184, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:35,979] Trial 30 finished with value: 0.7635009310986964 and parameters: {'classifier': 'gradientboost', 'n_estimators': 144, 'learning_rate': 0.03489392170728465, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:36,005] Trial 31 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.23208670067692785, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:36,030] Trial 32 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.17122303565842956, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:36,055] Trial 33 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.16904014025906933, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:36,080] Trial 34 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.41057313510916027, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:36,114] Trial 35 finished with value: 0.7579143389199255 and parameters: {'classifier': 'svm', 'C': 0.786181151983241, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:36,145] Trial 36 finished with value: 0.7337057728119181 and parameters: {'classifier': 'svm', 'C': 0.10375011439658065, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:36,171] Trial 37 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.3162884987295095, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:37,373] Trial 38 finished with value: 0.7616387337057727 and parameters: {'classifier': 'randomforest', 'n_estimators': 230, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:37,398] Trial 39 finished with value: 0.7746741154562384 and parameters: {'classifier': 'svm', 'C': 0.1889008585159804, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:38,382] Trial 40 finished with value: 0.7467411545623835 and parameters: {'classifier': 'gradientboost', 'n_estimators': 84, 'learning_rate': 0.035355488658730505, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:38,408] Trial 41 finished with value: 0.7802607076350093 and parameters: {'classifier': 'svm', 'C': 0.10452216561662372, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:38,432] Trial 42 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.1657692092307513, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:38,458] Trial 43 finished with value: 0.7783985102420856 and parameters: {'classifier': 'svm', 'C': 0.1432750499626447, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:38,483] Trial 44 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 0.330266780732727, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:39,941] Trial 45 finished with value: 0.7635009310986964 and parameters: {'classifier': 'randomforest', 'n_estimators': 295, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:39,967] Trial 46 finished with value: 0.7783985102420856 and parameters: {'classifier': 'svm', 'C': 0.10235584456329486, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:39,995] Trial 47 finished with value: 0.7281191806331471 and parameters: {'classifier': 'svm', 'C': 0.4352853186341979, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:40,067] Trial 48 finished with value: 0.7765363128491619 and parameters: {'classifier': 'svm', 'C': 9.593626782063666, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.
[I 2026-05-18 03:04:40,097] Trial 49 finished with value: 0.690875232774674 and parameters: {'classifier': 'svm', 'C': 50.30006770394413, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 21 with value: 0.7802607076350093.

In [64]:
print('Best accuracy', study.best_trial.value)
print("Best param", study.best_trial.params)

Best accuracy 0.7802607076350093
Best param {'classifier': 'svm', 'C': 0.1074710140811938, 'kernel': 'linear', 'gamma': 'auto'}

In [65]:
study.trials_dataframe()

    number     value  ... params_n_estimators     state
0        0  0.754190  ...               116.0  COMPLETE
1        1  0.776536  ...                 NaN  COMPLETE
2        2  0.739292  ...                 NaN  COMPLETE
3        3  0.756052  ...               161.0  COMPLETE
4        4  0.759777  ...               269.0  COMPLETE
5        5  0.703911  ...                 NaN  COMPLETE
6        6  0.759777  ...               239.0  COMPLETE
7        7  0.756052  ...               121.0  COMPLETE
8        8  0.696462  ...                 NaN  COMPLETE
9        9  0.748603  ...                81.0  COMPLETE
10      10  0.778399  ...                 NaN  COMPLETE
11      11  0.778399  ...                 NaN  COMPLETE
12      12  0.778399  ...                 NaN  COMPLETE
13      13  0.776536  ...                 NaN  COMPLETE
14      14  0.776536  ...                 NaN  COMPLETE
15      15  0.776536  ...                 NaN  COMPLETE
16      16  0.733706  ...               206.0  COMPLETE
17      17  0.776536  ...                 NaN  COMPLETE
18      18  0.757914  ...                 NaN  COMPLETE
19      19  0.752328  ...                52.0  COMPLETE
20      20  0.763501  ...                 NaN  COMPLETE
21      21  0.780261  ...                 NaN  COMPLETE
22      22  0.780261  ...                 NaN  COMPLETE
23      23  0.776536  ...                 NaN  COMPLETE
24      24  0.778399  ...                 NaN  COMPLETE
25      25  0.776536  ...                 NaN  COMPLETE
26      26  0.776536  ...                 NaN  COMPLETE
27      27  0.739292  ...                 NaN  COMPLETE
28      28  0.741155  ...               298.0  COMPLETE
29      29  0.759777  ...               184.0  COMPLETE
30      30  0.763501  ...               144.0  COMPLETE
31      31  0.776536  ...                 NaN  COMPLETE
32      32  0.776536  ...                 NaN  COMPLETE
33      33  0.776536  ...                 NaN  COMPLETE
34      34  0.776536  ...                 NaN  COMPLETE
35      35  0.757914  ...                 NaN  COMPLETE
36      36  0.733706  ...                 NaN  COMPLETE
37      37  0.776536  ...                 NaN  COMPLETE
38      38  0.761639  ...               230.0  COMPLETE
39      39  0.774674  ...                 NaN  COMPLETE
40      40  0.746741  ...                84.0  COMPLETE
41      41  0.780261  ...                 NaN  COMPLETE
42      42  0.776536  ...                 NaN  COMPLETE
43      43  0.778399  ...                 NaN  COMPLETE
44      44  0.776536  ...                 NaN  COMPLETE
45      45  0.763501  ...               295.0  COMPLETE
46      46  0.778399  ...                 NaN  COMPLETE
47      47  0.728119  ...                 NaN  COMPLETE
48      48  0.776536  ...                 NaN  COMPLETE
49      49  0.690875  ...                 NaN  COMPLETE

[50 rows x 16 columns]

In [66]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
svm              36
gradientboost     7
randomforest      7
Name: count, dtype: int64

In [67]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
gradientboost    0.749667
randomforest     0.758446
svm              0.764484
Name: value, dtype: float64

In [68]:
#plot history
plot_optimization_history(study).show()

In [69]:
plot_slice(study).show()

In [70]:
plot_param_importances(study).show()